name: python-learning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - numpy=1.21
  - pandas=2.0
  - matplotlib=3.4
  - beautifulsoup4=4.12
  - lxml=4.9
  - requests=2.31
  - mechanicalsoup=1.3
  - pytest=7.0
  - pytest-cov=4.0
  - black=22.0
  - flake8=5.0
  - isort=5.0
  - pip
  - pip:
    - PyPDF2>=3.0
    - pdfplumber>=0.10.0
    - collections-extended>=1.0
    - sphinx>=5.0.0
    - sphinx-rtd-theme>=1.0.0